FROM envoyproxy/envoy:v1.28.0
USER root

# Install tool tambahan & Consul CLI (ARM64)
ARG CONSUL_VERSION=1.21.1

RUN apt-get update && \
    apt-get install -y curl unzip bash gettext ca-certificates && \
    curl -Lo /tmp/consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_arm64.zip && \
    unzip /tmp/consul.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/consul && \
    rm -rf /tmp/* && \
    rm -rf /var/lib/apt/lists/*

# Copy entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]